# Generated by Django 5.1.5 on 2025-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0002_alter_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='languages',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Australia', 'Australia'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('China', 'China'), ('Russia', 'Russia'), ('Brazil', 'Brazil'), ('South Africa', 'South Africa'), ('Nigeria', 'Nigeria'), ('Mexico', 'Mexico'), ('Argentina', 'Argentina'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Denmark', 'Denmark'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('Hungary', 'Hungary'), ('Romania', 'Romania'), ('Bulgaria', 'Bulgaria'), ('Croatia', 'Croatia'), ('Slovenia', 'Slovenia'), ('Slovakia', 'Slovakia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Estonia', 'Estonia'), ('Ireland', 'Ireland'), ('Scotland', 'Scotland'), ('Wales', 'Wales'), ('Northern Ireland', 'Northern Ireland'), ('New Zealand', 'New Zealand'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Thailand', 'Thailand'), ('Indonesia', 'Indonesia'), ('Philippines', 'Philippines'), ('Vietnam', 'Vietnam'), ('South Korea', 'South Korea'), ('North Korea', 'North Korea'), ('Taiwan', 'Taiwan'), ('Hong Kong', 'Hong Kong'), ('Macau', 'Macau'), ('Bangladesh', 'Bangladesh'), ('Pakistan', 'Pakistan'), ('Sri Lanka', 'Sri Lanka'), ('Nepal', 'Nepal'), ('Bhutan', 'Bhutan'), ('Maldives', 'Maldives'), ('Afghanistan', 'Afghanistan'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Syria', 'Syria'), ('Lebanon', 'Lebanon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Super Admin', 'Super Admin')], max_length=50, null=True),
        ),
    ]
