# Generated by Django 5.1.5 on 2025-02-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_users_languages_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
