# Generated by Django 5.1.5 on 2025-02-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0003_remove_categories_order_alter_categories_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductServices.categories'),
        ),
    ]
