from django.db import models
from UserServices.models import Users
from ProductServices.models import Products

# Create your models here.

class PurchaseOrder(models.Model):
    id=models.AutoField(primary_key=True)
    warehouse_id=models.ForeignKey('InventoryServices.Warehouse', on_delete=models.CASCADE, blank=True, null=True, related_name='warehouse_id_purchase_order')
    supplier_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='supplier_id_purchase_order')
    last_updated_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='last_updated_by_user_id_purchase_order')
    po_code=models.CharField(max_length=255)
    po_date=models.DateTimeField()
    expected_delivery_date=models.DateTimeField()
    payment_terms=models.CharField(max_length=255, choices=[('CASH','CASH'),('CREDIT','CREDIT'),('ONLINE','ONLINE'),('CHEQUE','CHEQUE')], default='CASH')
    payment_status=models.CharField(max_length=255,choices=[('PAID','PAID'),('UNPAID','UNPAID'),('PARTIAL PAID','PARTIAL PAID'),('CANCELLED','CANCELLED')],default='UNPAID')
    total_amount=models.DecimalField(max_digits=10, decimal_places=2)
    paid_amount=models.DecimalField(max_digits=10, decimal_places=2)
    due_amount=models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount=models.DecimalField(max_digits=10, decimal_places=2)
    discount_type=models.CharField(max_length=255,choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT'),('NO DISCOUNT','NO DISCOUNT'),('ITEM DISCOUNT','ITEM DISCOUNT')],default='NO DISCOUNT')
    shipping_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_type=models.CharField(max_length=255, choices=[('FREE', 'FREE'), ('PAID', 'PAID')], default='FREE')
    shipping_tax_percentage=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_tax_amount=models.DecimalField(max_digits=10, decimal_places=2)
    additional_details=models.JSONField()
    status=models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('CREATED','CREATED'),('APPROVED','APPROVED'),('SENT','SENT'),('RECEIVED','RECEIVED'),('PARTIAL RECEIVED','PARTIAL RECEIVED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED'),('COMPLETE','COMPLETE')], default='DRAFT')
    created_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='created_by_user_id_purchase_order')
    updated_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='updated_by_user_id_purchase_order')
    domain_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='domain_user_id_purchase_order')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    approved_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='approved_by_user_id_purchase_order')
    approved_at=models.DateTimeField(blank=True, null=True)
    cancelled_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='cancelled_by_user_id_purchase_order')
    cancelled_at=models.DateTimeField(blank=True, null=True)
    cancelled_reason=models.TextField()
    received_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='received_by_user_id_purchase_order')
    received_at=models.DateTimeField()
    returned_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='returned_by_user_id_purchase_order')
    returned_at=models.DateTimeField()

class PurchaseOrderItems(models.Model):
    id=models.AutoField(primary_key=True)
    po_id=models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='po_id_purchase_order_items')
    product_id=models.ForeignKey(Products, on_delete=models.CASCADE, blank=True, null=True, related_name='product_id_purchase_order_items')
    quantity_order=models.IntegerField(default=0)
    quantity_received=models.IntegerField(default=0)
    quantity_cancelled=models.IntegerField(default=0)
    quantity_returned=models.IntegerField(default=0)
    buying_price=models.DecimalField(max_digits=10, decimal_places=2)
    selling_price=models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount=models.DecimalField(max_digits=10, decimal_places=2)
    amount_paid=models.DecimalField(max_digits=10, decimal_places=2)
    amount_retourned=models.DecimalField(max_digits=10, decimal_places=2)
    amount_cancelled=models.DecimalField(max_digits=10, decimal_places=2)
    amount_ordered=models.DecimalField(max_digits=10, decimal_places=2)
    tax_percentage=models.DecimalField(max_digits=10, decimal_places=2)
    tax_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_tax_amount=models.DecimalField(max_digits=10, decimal_places=2)
    discount_type=models.CharField(max_length=255,choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT'),('NO DISCOUNT','NO DISCOUNT'),('ITEM DISCOUNT','ITEM DISCOUNT')],default='NO DISCOUNT')
    additional_details=models.JSONField()
    status=models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('CREATED','CREATED'),('APPROVED','APPROVED'),('SENT','SENT'),('RECEIVED','RECEIVED'),('PARTIAL RECEIVED','PARTIAL RECEIVED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED'),('COMPLETE','COMPLETE')], default='DRAFT')
    created_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='created_by_user_id_purchase_order_items')
    updated_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='updated_by_user_id_purchase_order_items')
    domain_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='domain_user_id_purchase_order_items')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    approved_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='approved_by_user_id_purchase_order_items')
    approved_at=models.DateTimeField()
    cancelled_by_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True, related_name='cancelled_by_user_id_purchase_order_items')
    cancelled_at=models.DateTimeField()
    cancelled_reason=models.TextField()
    received_by_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='received_by_user_id_purchase_order_items')
    received_at=models.DateTimeField(null=True,blank=True)
    returned_by_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='returned_by_user_id_purchase_order_items')
    returned_at=models.DateTimeField()

class PurchaseOrderInwardedLog(models.Model):
    id=models.AutoField(primary_key=True)
    po_id=models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='po_id_po_inwarded_log')
    invoice_path=models.TextField()
    invoice_number=models.CharField(max_length=255)
    notes=models.CharField(max_length=255)
    inwarded_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='inwarded_by_user_id_po_inwarded_log')
    inwarded_at=models.DateTimeField()
    addition_details=models.JSONField()
    status=models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('RECEIVED','RECEIVED'),('PARTIAL RECEIVED','PARTIAL RECEIVED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED')], default='DRAFT')
    domain_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='domain_user_id_po_inwarded_log')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


class PurchaseOrderItemInwardedLog(models.Model):
    id=models.AutoField(primary_key=True)
    po_item_id=models.ForeignKey(PurchaseOrderItems, on_delete=models.CASCADE, blank=True, null=True, related_name='po_item_id_po_item_inwarded_log')
    inwarded_quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10, decimal_places=2)
    tax_percentage=models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount=models.DecimalField(max_digits=10, decimal_places=2)
    discount_type=models.CharField(max_length=255,choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT'),('NO DISCOUNT','NO DISCOUNT'),('ITEM DISCOUNT','ITEM DISCOUNT')],default='NO DISCOUNT')
    shipping_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_tax_percentage=models.DecimalField(max_digits=10, decimal_places=2)
    additional_details=models.JSONField()
    status=models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('RECEIVED','RECEIVED'),('PARTIAL RECEIVED','PARTIAL RECEIVED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED'),('COMPLETE','COMPLETE'), ('RETURNED', 'RETURNED')], default='DRAFT')
    domain_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='domain_user_id_po_item_inwarded_log')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class PurchaseOrderLogs(models.Model):
    id=models.AutoField(primary_key=True)
    po_id=models.ForeignKey(PurchaseOrder,on_delete=models.CASCADE,blank=True,null=True,related_name='po_id_purchase_order_logs')
    comment=models.TextField()
    created_by_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='created_by_user_id_purchase_order_logs')
    domain_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='domain_user_id_purchase_order_logs')
    additional_details=models.JSONField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

"""---------------------------------------------------------------------------------------------------------------------------------------------------------- """

class SalesOrder(models.Model):
    id=models.AutoField(primary_key=True)
    custommer_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='customer_id')
    last_updated_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='last_updated_by_user_id_sales_order')
    so_code=models.CharField(max_length=255)
    so_date=models.DateTimeField()
    expected_delivery_date=models.DateTimeField()
    payment_terms=models.CharField(max_length=255, choices=[('CASH','CASH'),('CREDIT','CREDIT'),('ONLINE','ONLINE'),('CHEQUE','CHEQUE')], default='CASH')
    payment_status=models.CharField(max_length=255,choices=[('PAID','PAID'),('UNPAID','UNPAID'),('PARTIAL PAID','PARTIAL PAID'),('CANCELLED','CANCELLED')],default='UNPAID')
    total_amount=models.DecimalField(max_digits=10, decimal_places=2)
    paid_amount=models.DecimalField(max_digits=10, decimal_places=2)
    due_amount=models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount=models.DecimalField(max_digits=10, decimal_places=2)
    discount_type=models.CharField(max_length=255,choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT'),('NO DISCOUNT','NO DISCOUNT'),('ITEM DISCOUNT','ITEM DISCOUNT')],default='NO DISCOUNT')
    shipping_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_type=models.CharField(max_length=255, choices=[('FREE', 'FREE'), ('PAID', 'PAID')], default='FREE')
    shipping_tax_percentage=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_tax_amount=models.DecimalField(max_digits=10, decimal_places=2)
    additional_details=models.JSONField()
    status=models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('DELIVERED','DELIVERED'),('PARTIAL DELIVERED','PARTIAL DELIVERED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED')], default='DRAFT')
    created_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='created_by_user_id_sales_order')
    updated_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='updated_by_user_id_sales_order')
    domain_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='domain_user_id_sales_order')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    approved_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='approved_by_user_id_sales_order')
    approved_at=models.DateTimeField(blank=True, null=True)
    cancelled_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='cancelled_by_user_id_sales_order')
    cancelled_at=models.DateTimeField(blank=True, null=True)
    cancelled_reason=models.TextField()
    received_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='received_by_user_id_sales_order')
    received_at=models.DateTimeField()
    returned_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='returned_by_user_id_sales_order')
    returned_at=models.DateTimeField()

class SalesOrderItems(models.Model):
    id=models.AutoField(primary_key=True)
    so_id=models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='so_id_sales_order_items')
    product_id=models.ForeignKey(Products, on_delete=models.CASCADE, blank=True, null=True, related_name='product_id_so_items')
    quantity_order=models.IntegerField(default=0)
    quantity_delivered=models.IntegerField(default=0)
    quantity_shipped=models.IntegerField(default=0)
    quantity_cancelled=models.IntegerField(default=0)
    quantity_returned=models.IntegerField(default=0)
    purchse_price=models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount=models.DecimalField(max_digits=10, decimal_places=2)
    amount_paid=models.DecimalField(max_digits=10, decimal_places=2)
    amount_retourned=models.DecimalField(max_digits=10, decimal_places=2)
    amount_cancelled=models.DecimalField(max_digits=10, decimal_places=2)
    amount_ordered=models.DecimalField(max_digits=10, decimal_places=2)
    tax_percentage=models.DecimalField(max_digits=10, decimal_places=2)
    tax_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_amount=models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_tax_amount=models.DecimalField(max_digits=10, decimal_places=2)
    discount_type=models.CharField(max_length=255,choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT')],default='PERCENTAGE')
    additional_details=models.JSONField()
    status=models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('DELIVERED','DELIVERED'),('PARTIAL DELIVERED','PARTIAL DELIVERED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED'), ('PARTIAL RETURNED','PARTIAL RETURNED')], default='DRAFT')
    created_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='created_by_user_id_sales_order_items')
    updated_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='updated_by_user_id_sales_order_items')
    domain_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='domain_user_id_sales_order_items')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    approved_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='approved_by_user_id_sales_order_items')
    approved_at=models.DateTimeField()
    cancelled_by_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True, related_name='cancelled_by_user_id_sales_order_items')
    cancelled_at=models.DateTimeField()
    cancelled_reason=models.TextField()
    shipped_by_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='shipped_by_user_id_sales_order_items')
    shipped_at=models.DateTimeField(null=True,blank=True)
    returned_by_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='returned_by_user_id_sales_order_items')
    returned_at=models.DateTimeField()

class SalesOrderOutwardedLog(models.Model): 
    id=models.AutoField(primary_key=True)
    so_id=models.ForeignKey(SalesOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='so_order_id')
    invoice_path=models.TextField()
    invoice_number=models.CharField(max_length=255)
    notes=models.CharField(max_length=255)
    outwarded_by_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='outwarded_by_user_id_so_outwarded_log')
    outwarded_at=models.DateTimeField()
    addition_details=models.JSONField()
    status=models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('DELIVERED','DELIVERED'),('PARTIAL DELIVERED','PARTIAL DELIVERED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED')], default='DRAFT')
    domain_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='domain_user_id_so_outwarded_log')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class SalesOrderItemOutwardedLog(models.Model):
    id=models.AutoField(primary_key=True)
    so_item_id=models.ForeignKey(PurchaseOrderItems, on_delete=models.CASCADE, blank=True, null=True, related_name='so_item_id')
    outwarded_quantity=models.IntegerField()
    inwarded_price=models.DecimalField(max_digits=10, decimal_places=2)
    inwarded_tax_percentage=models.DecimalField(max_digits=10, decimal_places=2)
    inwarded_discount_amount=models.DecimalField(max_digits=10, decimal_places=2)
    inwarded_discount_type=models.CharField(max_length=255,choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT')],default='PERCENTAGE')
    inwarded_shipping_amount=models.DecimalField(max_digits=10, decimal_places=2)
    inwarded_shipping_tax_percentage=models.DecimalField(max_digits=10, decimal_places=2)
    additional_details=models.JSONField()
    status=models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('DELIVERED','DELIVERED'),('PARTIAL DELIVERED','PARTIAL DELIVERED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED'),('COMPLETE','COMPLETE'), ('RETURNED', 'RETURNED')], default='DRAFT')
    domain_user_id=models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='domain_user_id_so_items_outwarded_log')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class SalesOrderLogs(models.Model):
    id=models.AutoField(primary_key=True)
    so_id=models.ForeignKey(PurchaseOrder,on_delete=models.CASCADE,blank=True,null=True,related_name='so_id')
    comment=models.TextField()
    created_by_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='created_by_user_id_sales_order_logs')
    domain_user_id=models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True,related_name='domain_user_id_sales_order_logs')
    additional_details=models.JSONField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
